### ISSUE TITLE
Manual ICA Issues

### ISSUE THREAD

**Issue by cgohil8** [OHBA-analysis/osl#123]
Steps to reproduce the error:
- Using the example script: https://github.com/OHBA-analysis/osl/blob/main/examples/oxford/dg_int_ext/3_manual_ica.py. by executing the line

```
python 3_manual_ica.py
```

via a terminal on hbaws46.
- A pop up appears.
- Initially, I can only see the 1st topo map on the left. If I move around the time series using the view, the remaining topo maps appear. 
- I can select the components I want to remove.
- When I close the pop-up, a blank 'Figure 1' box appears.
- I get an index error.

Full terminal output:
```
Loading dataset:
Reading /ohba/pi/knobre/cgohil/dg_int_ext/preproc/InEx_s01_block_01_tsss/InEx_s01_block_01_tsss_preproc_raw.fif
Opening raw data file /ohba/pi/knobre/cgohil/dg_int_ext/preproc/InEx_s01_block_01_tsss/InEx_s01_block_01_tsss_preproc_raw.fif...
    Range : 4750 ... 139749 =     19.000 ...   558.996 secs
Ready.
Reading /ohba/pi/knobre/cgohil/dg_int_ext/preproc/InEx_s01_block_01_tsss/InEx_s01_block_01_tsss_events.npy
Reading /ohba/pi/knobre/cgohil/dg_int_ext/preproc/InEx_s01_block_01_tsss/InEx_s01_block_01_tsss_ica.fif
Reading /ohba/pi/knobre/cgohil/dg_int_ext/preproc/InEx_s01_block_01_tsss/InEx_s01_block_01_tsss_ica.fif ...
Now restoring ICA solution ...
Ready.
Creating RawArray with float64 data, n_channels=55, n_times=135000
    Range : 4750 ... 139749 =     19.000 ...   558.996 secs
Ready.
Using matplotlib as 2D backend.
Traceback (most recent call last):
  File "/home/cgohil/local/miniconda3/envs/osl/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 287, in process
    func(*args, **kwargs)
  File "/home/cgohil/packages/oslpy/osl/preprocessing/plot_ica.py", line 1164, in _close
    tmp = tmp[0]
IndexError: list index out of range
```

**Comment by cgohil8** [comment]
@matsvanes, did you fix this? I don't get this error anymore on hbaws. If you cannot reproduce it, then you can close the issue.

**Comment by matsvanes** [comment]
I believe I fixed the indexing error in #122 . I was never able to reproduce the single topoplot that you mentioned, so if you don't get that anymore in your latest version, I think we're good :)

**Comment by cgohil8** [comment]
I still get the single topo map, but i don't think this is a big deal the rest appear as soon as you move around the time series. The index error is what I was referring to.

I also noticed when i've selected some ICA components and close the figure then I have to close a series of blank figures before the code continues. Is this the correct behaviour?

**Comment by matsvanes** [comment]
Ah, that is odd. I also don't get any extra figures when I close the interactive figure. Do you get the same behavior when using `ica.plot_sources(raw)`?

Which backend are you using? I'm using `TkAgg` in PyCharm on hbaws..

**Comment by cgohil8** [comment]
I am also using `TkAgg` on hbaws. What's `ica` and `raw` in:
```
ica.plot_sources(raw)
```
Are these MNE functions?

**Comment by matsvanes** [comment]
`ica` is https://mne.tools/stable/generated/mne.preprocessing.ICA.html
`raw` is https://mne.tools/stable/generated/mne.io.Raw.html

`plot_sources` is an MNE function https://mne.tools/stable/generated/mne.preprocessing.ICA.html#mne.preprocessing.ICA.plot_sources
